spring:
  application:
    name: donation
  neo4j:
    uri: ${AURA_URI}
    authentication:
      username: ${AURA_USER}
      password: ${AURA_PASSWORD}
    security:
      encrypted: true
  resources:
    cache:
      period: 0
    static-locations: classpath:/static/
  web:
    resources:
      add-mappings: true

server:
  base:
    url: http://localhost:8080

images:
  profile:
    dir: src/main/resources/static/images/users
  groups:
    dir: src/main/resources/static/images/groups
  defaultProfile:
    path: ./images/default/default.png
  defaultProfileGroup:
    path: ./images/default/group_default.png
  defaultLandscape:
    path: ./images/default/default_landscape.png
  defaultLandscapeGroup:
    path: ./images/default/group_default_landscape.png

servlet:
  multipart:
    enabled: true
    max-file-size: 10MB
    max-request-size: 10MB