spring:
  application:
    name: donation
  neo4j:
    uri: ${AURA_URI}
    authentication:
      username: ${AURA_USER}
      password: ${AURA_PASSWORD}
    security:
      encrypted: true
images:
  upload:
    dir: ./images/users
  default:
    path: ./images/default/default.jpg
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
